apiVersion: v1
kind: Service
metadata:
  name: security-agent
  namespace: security-agent
  labels:
    app: security-agent
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: security-agent
