"""Host enrollment: token generation, validation, install script rendering, registration."""

import hashlib
import secrets
from datetime import UTC, datetime, timedelta

from src.common.config.settings import get_settings
from src.common.logging.logger import get_logger

logger = get_logger(__name__)


INSTALL_SH = """#!/bin/bash
# ----------------------------------------------------------------------------
# Security Agent installer (generated by console /api/v1/agents/install)
# Recommended invocation (download as file, then execute) -- SINGLE LINE so
# it copy-pastes cleanly. Do NOT add \\ line continuations; the trailing
# backslash gets literalised by some terminals and breaks the next &&.
#
#     curl -fsSL "<console>/api/v1/agents/install?token=...&os=linux" -o secagent-install.sh && chmod +x secagent-install.sh && sudo bash secagent-install.sh
# ----------------------------------------------------------------------------
set -euo pipefail

TOKEN="__SECAGENT_TOKEN__"
CONSOLE="__SECAGENT_CONSOLE_URL__"
INSTALL_DIR="/opt/secagent"
CONFIG_DIR="/etc/secagent"
SERVICE_NAME="secagent"

log() { printf "[secagent] %s\n" "$*" >&2; }
die() { printf "[secagent][ERROR] %s\n" "$*" >&2; exit 1; }

# --- 1. Validate environment --------------------------------------------------
[ "$(id -u)" -eq 0 ] || die "Please run as root (sudo bash $0)."
command -v curl >/dev/null 2>&1 || die "curl is required."
command -v systemctl >/dev/null 2>&1 || die "systemctl is required (systemd-based distro)."

ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *)        die "Unsupported architecture: $ARCH" ;;
esac
log "Detected architecture: $ARCH"

# --- 2. Create install directories --------------------------------------------
mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"

# --- 3. Download agent binary (token via Authorization header, NOT in URL) --
# Note: we deliberately do NOT use ``--fail`` here so we can capture the
# server's error body on HTTP 4xx/5xx (which usually contains the build hint).
BIN_URL="$CONSOLE/api/v1/agents/binary/linux/$ARCH"
log "Downloading agent binary from $CONSOLE ..."
# Capture status code separately from the curl exit code so a partial-
# write / connection-close after the body does not trigger the "000"
# fallback to be concatenated with curl's "-w" output.
HTTP_CODE=$(curl -sS -o "$INSTALL_DIR/agent" -w "%{http_code}" \\
    -H "Authorization: Bearer $TOKEN" "$BIN_URL" 2>/dev/null) || true
# If curl exited non-zero, HTTP_CODE may be empty -> treat as 000. If
# curl wrote the body successfully but exited weirdly (e.g. server
# closed connection mid-stream), HTTP_CODE will be the real status
# (e.g. "200") and the file will contain the binary; we let that path
# succeed.
HTTP_CODE="${HTTP_CODE:-000}"
# Treat as success if EITHER curl reported 200 OR the file is a valid ELF
# binary (covers the case where curl exited non-zero after writing the body).
IS_ELF=0
if [ -s "$INSTALL_DIR/agent" ] && head -c 4 "$INSTALL_DIR/agent" 2>/dev/null | grep -aq "ELF"; then
    IS_ELF=1
fi
if [ "$HTTP_CODE" != "200" ] && [ "$IS_ELF" -ne 1 ]; then
    SERVER_MSG=$(head -c 400 "$INSTALL_DIR/agent" 2>/dev/null || true)
    rm -f "$INSTALL_DIR/agent"
    cat >&2 <<EOF
[secagent][ERROR] Agent binary download failed.
  URL        : $BIN_URL
  HTTP code  : $HTTP_CODE
  Server said: $SERVER_MSG

Most common cause: the agent binary was never built on the console side.
Fix it from the console repo:

    cd agent
    make build-linux-amd64       # (or build-linux-arm64)

Then re-run this installer. The installer is idempotent: it will re-download
and re-register the host.
EOF
    exit 1
fi
chmod 0750 "$INSTALL_DIR/agent"
install_nuclei || true
install_nuclei_templates || true

# --- 4. Optional CA cert (best-effort) ----------------------------------------
curl -fsSL --fail -H "Authorization: Bearer $TOKEN" "$CONSOLE/api/v1/agents/ca" -o "$CONFIG_DIR/ca.pem" 2>/dev/null \
    || log "CA cert not available (continuing without)."

# --- 4b. Best-effort nuclei CLI download (P0 / 2026-07-18) ---------------------
# The Go agent ships a runNuclei() path that shells out to /opt/secagent/bin/nuclei.
# We download it from the official projectdiscovery/nuclei release. The download
# is best-effort: matcher-only mode still works without nuclei, so we swallow
# failures with `|| true` and never abort the install.
install_nuclei() {
    mkdir -p "$INSTALL_DIR/bin"
    log "Downloading nuclei CLI (best-effort) from GitHub release..."
    local NUCLEI_VERSION="v3.3.0"
    local NUCLEI_TARBALL="nuclei_${NUCLEI_VERSION}_linux_${ARCH}.zip"
    local TMPDIR_NUC=$(mktemp -d)
    if curl -fsSL --fail -o "$TMPDIR_NUC/$NUCLEI_TARBALL" \
        "https://github.com/projectdiscovery/nuclei/releases/download/${NUCLEI_VERSION}/${NUCLEI_TARBALL}" 2>/dev/null; then
        (cd "$TMPDIR_NUC" && (command -v unzip >/dev/null && unzip -o "$NUCLEI_TARBALL" || python3 -c "import zipfile,sys; zipfile.ZipFile(sys.argv[1]).extractall('.')" "$NUCLEI_TARBALL")) >/dev/null 2>&1
        if [ -x "$TMPDIR_NUC/nuclei" ]; then
            install -m 0755 "$TMPDIR_NUC/nuclei" "$INSTALL_DIR/bin/nuclei"
            log "nuclei installed at $INSTALL_DIR/bin/nuclei"
        else
            log "nuclei tarball downloaded but binary not found -- matcher-only mode will be used"
        fi
    else
        log "nuclei download failed -- matcher-only mode will be used"
    fi
    rm -rf "$TMPDIR_NUC"
}

# --- 4c. Best-effort nuclei templates sync (P1-GO-4 / 2026-07-19) ------------
# The Go agent's nuclei runner reads templates from $INSTALL_DIR/templates.
# nuclei ships its own -update flag, but the bundled templates are huge
# (multi-thousand templates) so we skip them here and instead drop a small
# "critical" subset pulled from nuclei-templates (the official repo) so the
# scanner has something to work with on a fresh host. Best-effort: failure
# here just means matcher-only mode until the next console-driven
# rule_update delivers a fresh manifest.
install_nuclei_templates() {
    mkdir -p "$INSTALL_DIR/templates"
    log "Downloading nuclei templates subset (best-effort)..."
    local TEMPLATES_VERSION="v9.6.0"
    local TARBALL="nuclei-templates-${TEMPLATES_VERSION}.tar.gz"
    local TMPDIR_TPL=$(mktemp -d)
    if curl -fsSL --fail -o "$TMPDIR_TPL/$TARBALL" \
        "https://github.com/projectdiscovery/nuclei-templates/archive/refs/tags/${TEMPLATES_VERSION}.tar.gz" 2>/dev/null; then
        (cd "$TMPDIR_TPL" && tar -xzf "$TARBALL" 2>/dev/null) || true
        # Copy just the cves/ + exposures/ subsets -- enough for "real CVE scan"
        # without bloating install from tens of thousands of templates.
        if [ -d "$TMPDIR_TPL/nuclei-templates-${TEMPLATES_VERSION#v}/cves" ]; then
            cp -r "$TMPDIR_TPL/nuclei-templates-${TEMPLATES_VERSION#v}/cves" "$INSTALL_DIR/templates/" 2>/dev/null || true
        fi
        if [ -d "$TMPDIR_TPL/nuclei-templates-${TEMPLATES_VERSION#v}/exposures" ]; then
            cp -r "$TMPDIR_TPL/nuclei-templates-${TEMPLATES_VERSION#v}/exposures" "$INSTALL_DIR/templates/" 2>/dev/null || true
        fi
        log "nuclei templates installed at $INSTALL_DIR/templates/"
    else
        log "nuclei templates download failed -- matcher-only mode will be used until server pushes templates"
    fi
    rm -rf "$TMPDIR_TPL"
}

# --- 5. systemd unit (enable now, start later once config has credentials) ---
cat > /etc/systemd/system/${SERVICE_NAME}.service <<EOFSVC
[Unit]
Description=Security Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/agent
Restart=always
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOFSVC
systemctl daemon-reload
systemctl enable ${SERVICE_NAME}.service

# --- 6. Register the host with the console (returns agent_id + agent_token) ----
HOSTNAME=$(hostname)
IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
KERNEL=$(uname -r)
log "Registering host $HOSTNAME with console..."

REG_BODY=$(cat <<EOFBODY
{"token":"$TOKEN","hostname":"$HOSTNAME","os":"linux","arch":"$ARCH","ip":"$IP","kernel":"$KERNEL"}
EOFBODY
)

REG_RESP=$(curl -fsSL --fail -X POST -H "Content-Type: application/json" -d "$REG_BODY" \
    "$CONSOLE/api/v1/agents/enroll" || echo "")

if [ -z "$REG_RESP" ]; then
    log "WARNING: registration failed -- agent is installed but not enrolled. Retry by re-running this script."
    # Empty credentials -> service will refuse to start until /enroll succeeds.
    AGENT_ID=""
    AGENT_TOKEN=""
    RULE_VERSION=""
else
    log "Host registered successfully."
    # Pull agent_id / agent_token out of the JSON response. Prefer python3
    # (always available on Rocky / RHEL / Debian family) and fall back to sed.
    if command -v python3 >/dev/null 2>&1; then
        AGENT_ID=$(printf '%s' "$REG_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('agent_id',''))")
        AGENT_TOKEN=$(printf '%s' "$REG_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('agent_token',''))")

        # P1 (2026-07-17): also pull rule_version so the host UI shows a real
        # value immediately instead of "-" until the server pushes rule_update.
        RULE_VERSION=$(printf '%s' "$REG_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('rule_version',''))")

        # P0-GO-1 (2026-07-19): pull the server Ed25519 public key too. Without
        # it in config.json the agent skips SetPublicKey (AgentID already set),
        # crypto.PublicKey stays nil, and the first signed scan_command panics
        # in ed25519.Verify -> crash loop.
        SERVER_PUBKEY=$(printf '%s' "$REG_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('server_public_key',''))")
    else
        AGENT_ID=$(printf '%s' "$REG_RESP" | grep -o '"agent_id"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
        AGENT_TOKEN=$(printf '%s' "$REG_RESP" | grep -o '"agent_token"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
        RULE_VERSION=$(printf '%s' "$REG_RESP" | grep -o '"rule_version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
        SERVER_PUBKEY=$(printf '%s' "$REG_RESP" | grep -o '"server_public_key"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
    fi
fi

if [ -z "$AGENT_ID" ] || [ -z "$AGENT_TOKEN" ]; then
    log "WARNING: registered but did not receive agent_id/agent_token -- service will not start until you re-run."
fi

# --- 7. Persist config with the real agent_id / agent_token -------------------
# Heredoc is UNQUOTED so bash expands $CONSOLE / $CONFIG_DIR / $AGENT_ID /
# $AGENT_TOKEN. The agent reads agent_token to authenticate its WS handshake
# (PG-backed via validate_agent_token). File mode 0600 keeps the token
# readable by root only.
cat > "$CONFIG_DIR/config.json" <<EOFCFG
{"console_url": "$CONSOLE", "ca_path": "$CONFIG_DIR/ca.pem", "agent_id": "$AGENT_ID", "agent_token": "$AGENT_TOKEN", "rule_version": "$RULE_VERSION", "server_public_key": "$SERVER_PUBKEY"}
EOFCFG
chmod 0600 "$CONFIG_DIR/config.json"

# --- 8. Start the service now that config.json has the credentials ----------
if [ -n "$AGENT_ID" ] && [ -n "$AGENT_TOKEN" ]; then
    systemctl restart ${SERVICE_NAME}.service
else
    log "Skipping systemctl restart -- no credentials yet. Re-run this script after the console is reachable."
fi

log "Installation complete. Service: ${SERVICE_NAME} (status: $(systemctl is-active ${SERVICE_NAME} 2>/dev/null || echo unknown))"
"""


INSTALL_PS1 = """#Requires -RunAsAdministrator
$ErrorActionPreference = "Stop"
$TOKEN = "__SECAGENT_TOKEN__"
$CONSOLE = "__SECAGENT_CONSOLE_URL__"
$INSTALL_DIR = "$env:ProgramData\\secagent"
$CONFIG_DIR = "$INSTALL_DIR\\config"
New-Item -ItemType Directory -Force -Path $INSTALL_DIR, $CONFIG_DIR | Out-Null
$ARCH = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "amd64" }
$BIN_URL = "$CONSOLE/api/v1/agents/binary/windows/$ARCH"
Invoke-WebRequest -Uri "$BIN_URL?token=$TOKEN" -OutFile "$INSTALL_DIR\agent.exe"
@{"console_url":"$CONSOLE","ca_path":"$CONFIG_DIR\\ca.pem","enroll_token":"$TOKEN"} | ConvertTo-Json | Out-File -Encoding utf8 "$CONFIG_DIR\\config.json"
New-Service -Name "SecAgent" -BinaryPathName "$INSTALL_DIR\agent.exe" -DisplayName "Security Agent" -StartupType Automatic
Start-Service -Name "SecAgent"
$HOSTNAME = $env:COMPUTERNAME
$IP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object InterfaceAlias -notmatch "Loopback" | Select-Object -First 1).IPAddress
$KERNEL = [System.Environment]::OSVersion.VersionString
$BODY = @{token="$TOKEN",hostname="$HOSTNAME",os="windows",arch="$ARCH",ip="$IP",kernel="$KERNEL"} | ConvertTo-Json
Invoke-RestMethod -Uri "$CONSOLE/api/v1/agents/enroll" -Method Post -Body $BODY -ContentType "application/json"
"""


async def create_enroll_token(
    group: str | None = None, ttl_hours: int = 24, uses: int = 1, created_by: str = "system"
) -> tuple[str, str]:
    """Generate an enrollment token (PG-backed). Returns (token, expires)."""
    from src.common.db.pg import get_pg_pool

    pool = await get_pg_pool()
    token = secrets.token_urlsafe(32)
    expires = datetime.now(UTC) + timedelta(hours=ttl_hours)
    await pool.execute(
        "INSERT INTO enroll_tokens (token, group_name, expires_at, uses_remaining, created_by) VALUES ($1, $2, $3, $4, $5)",
        token,
        group,
        expires,
        uses,
        created_by,
    )
    logger.info("enroll_token_created", token_preview=token[:8])
    return token, expires.isoformat()


async def peek_enroll_token(token: str) -> dict | None:
    """Validate token WITHOUT consuming uses.  Returns {group} or None.

    Used by /install, /binary, /ca endpoints that should not consume
    the enrollment token (only /enroll should decrement uses).
    """
    from src.common.db.pg import get_pg_pool

    pool = await get_pg_pool()
    row = await pool.fetchrow(
        "SELECT group_name, expires_at, uses_remaining FROM enroll_tokens WHERE token = $1",
        token,
    )
    if not row:
        return None
    if datetime.now(UTC) > row["expires_at"]:
        await pool.execute("DELETE FROM enroll_tokens WHERE token = $1", token)
        return None
    if row["uses_remaining"] <= 0:
        await pool.execute("DELETE FROM enroll_tokens WHERE token = $1", token)
        return None
    return {"group": row["group_name"] or ""}


async def validate_enroll_token(token: str) -> dict | None:
    """Validate token; decrement uses (PG). Returns {group} or None."""
    from src.common.db.pg import get_pg_pool

    pool = await get_pg_pool()
    row = await pool.fetchrow(
        "SELECT group_name, expires_at, uses_remaining FROM enroll_tokens WHERE token = $1",
        token,
    )
    if not row:
        return None
    if datetime.now(UTC) > row["expires_at"]:
        await pool.execute("DELETE FROM enroll_tokens WHERE token = $1", token)
        return None
    if row["uses_remaining"] <= 0:
        await pool.execute("DELETE FROM enroll_tokens WHERE token = $1", token)
        return None
    remaining = await pool.fetchval(
        "UPDATE enroll_tokens SET uses_remaining = uses_remaining - 1 WHERE token = $1 AND uses_remaining > 0 RETURNING uses_remaining",
        token,
    )
    if remaining is not None and remaining <= 0:
        await pool.execute("DELETE FROM enroll_tokens WHERE token = $1", token)
    return {"group": row["group_name"] or ""}


def get_install_script_content(token: str, os_type: str, console_url: str | None = None) -> str:
    """Return the appropriate install script for the given OS.

    Uses simple token substitution (not str.format) so that bash / PowerShell
    constructs that contain literal ``{`` and ``}`` (JSON, awk scripts, etc.)
    do not need to be double-escaped.
    """
    url = console_url or get_settings().agent_console_external_url
    template = INSTALL_PS1 if os_type == "windows" else INSTALL_SH
    return template.replace("__SECAGENT_TOKEN__", token).replace("__SECAGENT_CONSOLE_URL__", url)


async def register_enroll_token(agent_id: str, agent_token: str, ttl_days: int = 365) -> None:
    """Store agent auth token hash in PG for WS authentication."""
    from src.common.db.pg import get_pg_pool

    pool = await get_pg_pool()
    token_hash = hashlib.sha256(agent_token.encode()).hexdigest()
    await pool.execute(
        "INSERT INTO agent_tokens (agent_id, token_hash) VALUES ($1, $2) "
        "ON CONFLICT (agent_id) DO UPDATE SET token_hash = $2, issued_at = NOW(), revoked_at = NULL",
        agent_id,
        token_hash,
    )


async def validate_agent_token(agent_id: str, token: str) -> bool:
    """Validate agent token against PG (for WS gateway auth).

    Logs the specific failure reason (no such agent / token mismatch /
    token revoked) so the operator can tell the difference from the
    server log instead of having to crack open psql."""
    from src.common.db.pg import get_pg_pool

    pool = await get_pg_pool()
    token_hash = hashlib.sha256(token.encode()).hexdigest()
    # Distinguish the three failure modes -- the agent process just keeps
    # retrying on a tight loop otherwise and there is no way to know
    # whether it is pointing at the wrong host or the wrong token.
    row = await pool.fetchrow(
        "SELECT token_hash, revoked_at FROM agent_tokens WHERE agent_id = $1",
        agent_id,
    )
    if row is None:
        logger.warning("agent_auth_failed_no_such_agent", agent_id=agent_id)
        return False
    if row["revoked_at"] is not None:
        logger.warning("agent_auth_failed_token_revoked", agent_id=agent_id)
        return False
    if row["token_hash"] != token_hash:
        logger.warning(
            "agent_auth_failed_token_mismatch",
            agent_id=agent_id,
            stored_hash_prefix=row["token_hash"][:8],
            incoming_hash_prefix=token_hash[:8],
        )
        return False
    return True
